import type { Metadata } from "next";
import "./ui/globals.css";
import {Providers} from "./Providers";
import {inter} from "@/app/ui/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${inter.className} antialiase`}>{children}
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  );
}
